# gans/configs/dcgan.yaml
seed: 42

# -------- dataset / loader --------
data:
  data_dir: "/home/student2/histo/data/lung_colon_image_set/lung_image_sets/lung_scc"
  img_size: 128
  batch_size: 32
  num_workers: 4
  val_split: 0.05

# -------- model --------
model:
  img_size: 128
  latent_dim: 128
  base_channels: 64
  lr: 0.0002

# -------- trainer --------
gpus: 1        # ile GPU chcesz użyć
max_epochs: 200