# gans/configs/ganformer.yaml
seed: 42
model_type: ganformer # <-- Nowy parametr

# -------- dataset / loader --------
data:
  data_dir: "outputs"
  img_size: 256
  batch_size: 32
  num_workers: 0
  val_split: 0.5

# -------- model --------
model:
  img_size: 64
  latent_dim: 100
  ngf: 64
  ndf: 64
  lr: 0.0002

# -------- trainer --------
trainer:
  epochs: 200
  gpus: 1