defaults:
  - override /hydra/sweeper: ax
  - override /hydra/launcher: joblib

hydra:
  sweeper:
    ax_config:
      max_trials: 10
    search_space:
      model.lr:
        type: range
        bounds: [0.0001, 0.001]
      model.batch_size:
        type: choice
        values: [8, 16, 32]
  launcher:
    n_jobs: 4
