name: CML
on: [push]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: iterative/setup-cml@v1
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install dvc[s3]
      - name: Run DVC pipeline
        run: |
          dvc pull
          dvc repro
          dvc push
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - name: Create CML report
        run: |
          dvc metrics diff --show-md >> report.md
          cml-send-comment report.md
        env:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
